package scheduler

func GetCursorVisitToken(token string) string {
	print("in get cursor visit token")
	return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhdXRoMHx1c2VyXzAxSlAwWTJNRVhNN0YzRVdOMFhLMEJCRzI0IiwidGltZSI6IjE3NDE2NDA3OTkiLCJyYW5kb21uZXNzIjoiMGE4YWI2ZDgtZjU2OC00YjYyIiwiZXhwIjo0MzMzNjQwNzk5LCJpc3MiOiJodHRwczovL2F1dGhlbnRpY2F0aW9uLmN1cnNvci5zaCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJhdWQiOiJodHRwczovL2N1cnNvci5jb20ifQ.cDRBAANUcQmKQJWyyDRlRufIVgUQukROR5VtDITwuUw"
}
