package routes

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestRunStopAndCertHTTPIntegration(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	stopReq := httptest.NewRequest(http.MethodPost, "/api/run/stop", bytes.NewReader([]byte(`{}`)))
	stopReq.Header.Set("Content-Type", "application/json")
	stopRec := httptest.NewRecorder()
	mux.ServeHTTP(stopRec, stopReq)

	if stopRec.Code != http.StatusOK {
		t.Fatalf("run stop http status=%d body=%s", stopRec.Code, stopRec.Body.String())
	}

	var stopResp map[string]interface{}
	if err := json.Unmarshal(stopRec.Body.Bytes(), &stopResp); err != nil {
		t.Fatalf("decode run stop response failed: %v", err)
	}

	stopData, _ := stopResp["data"].(map[string]interface{})
	if stopData["error"] != "not_running" {
		t.Fatalf("expected run stop error=not_running, got %#v", stopData["error"])
	}

	exportReq := httptest.NewRequest(http.MethodPost, "/api/cert/export", bytes.NewReader([]byte(`{"cert_type":"root-ca"}`)))
	exportReq.Header.Set("Content-Type", "application/json")
	exportRec := httptest.NewRecorder()
	mux.ServeHTTP(exportRec, exportReq)

	if exportRec.Code != http.StatusOK {
		t.Fatalf("cert export http status=%d body=%s", exportRec.Code, exportRec.Body.String())
	}

	statusReq := httptest.NewRequest(http.MethodGet, "/api/cert/status?cert_type=root-ca", nil)
	statusRec := httptest.NewRecorder()
	mux.ServeHTTP(statusRec, statusReq)

	if statusRec.Code != http.StatusOK {
		t.Fatalf("cert status http status=%d body=%s", statusRec.Code, statusRec.Body.String())
	}

	var statusResp map[string]interface{}
	if err := json.Unmarshal(statusRec.Body.Bytes(), &statusResp); err != nil {
		t.Fatalf("decode cert status response failed: %v", err)
	}

	statusData, _ := statusResp["data"].(map[string]interface{})
	if statusData["cert_type"] != "root-ca" {
		t.Fatalf("expected cert_type=root-ca, got %#v", statusData["cert_type"])
	}

	downloadReq := httptest.NewRequest(http.MethodGet, "/api/cert/download?cert_type=root-ca", nil)
	downloadRec := httptest.NewRecorder()
	mux.ServeHTTP(downloadRec, downloadReq)

	if downloadRec.Code != http.StatusOK {
		t.Fatalf("cert download http status=%d body=%s", downloadRec.Code, downloadRec.Body.String())
	}

	if contentDisposition := downloadRec.Header().Get("Content-Disposition"); !strings.Contains(contentDisposition, "root-ca.pem") {
		t.Fatalf("unexpected Content-Disposition: %s", contentDisposition)
	}
}

func TestAPIDocsAutoGeneratedFromRoutes(t *testing.T) {
	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	jsonReq := httptest.NewRequest(http.MethodGet, "/api-docs/openapi.json", nil)
	jsonRec := httptest.NewRecorder()
	mux.ServeHTTP(jsonRec, jsonReq)

	if jsonRec.Code != http.StatusOK {
		t.Fatalf("openapi status=%d body=%s", jsonRec.Code, jsonRec.Body.String())
	}

	if contentType := jsonRec.Header().Get("Content-Type"); !strings.Contains(contentType, "application/json") {
		t.Fatalf("unexpected openapi content-type: %s", contentType)
	}

	body := jsonRec.Body.String()
	if !strings.Contains(body, "\"/api/run/start\"") {
		t.Fatalf("openapi missing expected route /api/run/start: %s", body)
	}

	if !strings.Contains(body, "\"/api/chat/completions\"") {
		t.Fatalf("openapi missing expected route /api/chat/completions: %s", body)
	}

	if strings.Contains(body, "\"/api/chat/completions\":{\"delete\":") {
		t.Fatalf("openapi should not include unsupported DELETE method for /api/chat/completions: %s", body)
	}

	if !strings.Contains(body, "\"/api/chat/completions\":{\"post\":") {
		t.Fatalf("openapi should include POST method for /api/chat/completions: %s", body)
	}

	if !strings.Contains(body, "\"summary\":\"POST /api/chat/completions\"") {
		t.Fatalf("openapi should include summary for POST /api/chat/completions: %s", body)
	}

	if !strings.Contains(body, "\"requestBody\":") {
		t.Fatalf("openapi should include requestBody for body-capable methods: %s", body)
	}

	uiReq := httptest.NewRequest(http.MethodGet, "/api-docs/index.html", nil)
	uiRec := httptest.NewRecorder()
	mux.ServeHTTP(uiRec, uiReq)

	if uiRec.Code != http.StatusOK {
		t.Fatalf("swagger ui status=%d body=%s", uiRec.Code, uiRec.Body.String())
	}

	if !strings.Contains(uiRec.Body.String(), "SwaggerUIBundle") {
		t.Fatalf("swagger ui page not rendered correctly")
	}
}
